name       : libusd
version    : '22.03'
release    : 8
source     :
    - https://github.com/PixarAnimationStudios/USD/archive/refs/tags/v22.03.tar.gz : 594910eab72168e47f48b5b02dbbdaf77084b1de717091b1104b6527e75d327a
homepage   : https://graphics.pixar.com/usd/docs/index.html
license    : Apache-2.0
component  : programming
summary    : Universal Scene Description
description: |
    Universal Scene Description (USD) is an efficient, scalable system for authoring, reading, and streaming time-sampled scene description for interchange between graphics applications.
clang      : yes
builddeps  :
    - pkgconfig(OpenEXR)
    - pkgconfig(OpenImageIO)
    - pkgconfig(Qt5Core)
    - pkgconfig(draco)
    - pkgconfig(glew)
    - pkgconfig(hdf5)
    - pkgconfig(oslquery)
    - pkgconfig(pyside2)
    - pkgconfig(x11)
    - alembic-devel
    - embree-devel
    - intel-tbb-devel
    - libboost-devel
    - opensubdiv-devel
    - openvdb-devel
    - ptex-devel
    - python-jinja
    - python-opengl
    - python-pyside2-tools
rundeps    :
    - python-pyside2
    - python-opengl
environment: |
    export LDFLAGS="$LDFLAGS -Wl,--allow-shlib-undefined"
setup      : |
    %apply_patches

    %cmake_ninja \
        -DCMAKE_SKIP_INSTALL_RPATH=ON \
        -DCMAKE_CXX_STANDARD=17 \
        -DPXR_BUILD_EXAMPLES=OFF \
        -DPXR_BUILD_TESTS=OFF \
        -DPXR_BUILD_TUTORIALS=OFF \
        -DPXR_BUILD_MONOLITHIC=ON \
        -DPXR_BUILD_ALEMBIC_PLUGIN=ON \
        -DPXR_BUILD_DRACO_PLUGIN=ON \
        -DPXR_BUILD_EMBREE_PLUGIN=ON \
        -DPXR_BUILD_OPENCOLORIO_PLUGIN=OFF \
        -DPXR_BUILD_OPENIMAGEIO_PLUGIN=ON \
        -DPXR_ENABLE_OPENVDB_SUPPORT=ON \
        -DPXR_ENABLE_OSL_SUPPORT=ON \
        -DPXR_ENABLE_VULKAN_SUPPORT=OFF \
        -DPXR_USE_PYTHON_3=ON \
        -DPYTHON_EXECUTABLE=/usr/bin/python3 \
        -DTBB_USE_DEBUG_BUILD=OFF \
        -DLIB_SUFFIX=64
build      : |
    %ninja_build
install    : |
    %ninja_install
    install -Dm00644 $pkgfiles/org.openusd.usdview.desktop -t $installdir/usr/share/applications
    rm -rf $installdir/usr/plugin
