name       : libusd
version    : '21.8'
release    : 4
source     :
    - https://github.com/PixarAnimationStudios/USD/archive/refs/tags/v21.08.tar.gz : c124c2d99922800f82dcbd0765d38a4f79443880e550ecb1e0532a334f359526
homepage   : https://graphics.pixar.com/usd/docs/index.html
license    : Apache-2.0
component  : programming
summary    : Universal Scene Description
description: |
    Universal Scene Description (USD) is an efficient, scalable system for authoring, reading, and streaming time-sampled scene description for interchange between graphics applications.
builddeps  :
    - pkgconfig(OpenEXR)
    - pkgconfig(OpenImageIO)
    - pkgconfig(Qt5Core)
    - pkgconfig(draco)
    - pkgconfig(glew)
    - pkgconfig(hdf5)
    - pkgconfig(oslquery)
    - pkgconfig(pyside2)
    - pkgconfig(x11)
    - alembic-devel
    - embree-devel
    - intel-tbb-devel
    - libboost-devel
    - opensubdiv-devel
    - openvdb-devel
    - ptex-devel
    - python-jinja
    - python-opengl
    - python-pyside2-tools
rundeps    :
    - python-pyside2
    - python-opengl
setup      : |
    %apply_patches

    %cmake_ninja \
        -DPXR_BUILD_EXAMPLES=OFF \
        -DCMAKE_CXX_FLAGSAKE_SKIP_BUILD_RPATH=ON \
        -DCMAKE_SKIP_INSTALL_RPATH=ON \
        -DPXR_BUILD_TESTS=OFF \
        -DPXR_BUILD_TUTORIALS=OFF \
        -DPXR_BUILD_MONOLITHIC=ON \
        -DPXR_BUILD_ALEMBIC_PLUGIN=ON \
        -DPXR_BUILD_DRACO_PLUGIN=ON \
        -DPXR_BUILD_EMBREE_PLUGIN=ON \
        -DPXR_BUILD_OPENCOLORIO_PLUGIN=OFF \
        -DPXR_BUILD_OPENIMAGEIO_PLUGIN=ON \
        -DPXR_ENABLE_OPENVDB_SUPPORT=ON \
        -DPXR_ENABLE_OSL_SUPPORT=ON \
        -DPXR_USE_PYTHON_3=ON \
        -DPYTHON_EXECUTABLE=/usr/bin/python3 \
        -DTBB_USE_DEBUG_BUILD=OFF \
        -DLIB_SUFFIX=64
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/plugin
