name       : libusd
version    : '20.11'
release    : 1
source     :
    - https://github.com/PixarAnimationStudios/USD/archive/v20.11.tar.gz : adbdf451a10a7af201b0fafa44ebc27cc2c3b412d3dbbd90f1a9319abe2e203d
homepage   : https://graphics.pixar.com/usd/docs/index.html
license    : Apache-2.0
component  : programming
summary    : Universal Scene Description
description: |
    Universal Scene Description (USD) is an efficient, scalable system for authoring, reading, and streaming time-sampled scene description for interchange between graphics applications.
builddeps  :
    - pkgconfig(glew)
    - pkgconfig(x11)
    - intel-tbb-devel
    - libboost-devel
    - python-jinja
setup      : |
    %patch -p1 < $pkgfiles/libusd-soversion.patch
    %patch -p1 < $pkgfiles/pxrconfig-cmake.patch
    %cmake_ninja \
        -DPXR_ENABLE_PYTHON_SUPPORT=OFF -DPXR_BUILD_TESTS=OFF -DPXR_BUILD_IMAGING=OFF \
        -DPXR_BUILD_EXAMPLES=OFF -DPXR_BUILD_TUTORIALS=OFF \
        -DPXR_ENABLE_PTEX_SUPPORT=OFF -DPXR_BUILD_USDVIEW=OFF -DPXR_BUILD_MONOLITHIC=ON \
        -DLIB_SUFFIX=64
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -r $installdir/usr/plugin
